### ISSUE TITLE
Libraries and cmake/pkgconfig files should be installed in arch dependent directory

### ISSUE THREAD

**Issue by StefanBruens** [cburstedde/libsc#106]
**Description**

The cmake `install` statement use a hardcoded "lib" destination, while on most Linux distributions the directory is arch specific.

The best solution is to use CMAKE_INSTALL_LIBDIR from [GNUInstallDirs](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html).

**Comment by StefanBruens** [comment]
Concatenating `CMAKE_INSTALL_PREFIX` and `CMAKE_INSTALL_LIBDIR` is wrong in the general case, please use `CMAKE_INSTALL_FULL_LIBDIR`  instead:

https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html#result-variables
> `CMAKE_INSTALL_<dir>`  
Destination for files of a given type. This value may be passed to the DESTINATION options of [install()](https://cmake.org/cmake/help/latest/command/install.html#command:install) commands for the corresponding file type. It should typically be a path relative to the installation prefix so that it can be converted to an absolute path in a relocatable way (see `CMAKE_INSTALL_FULL_<dir>`). **However, an absolute path is also allowed.**

**Comment by cburstedde** [comment]
Thanks; any remaining comments?
Appreciate the attention to detail.

**Comment by StefanBruens** [comment]
Regressed by #121, please reopen
