### ISSUE TITLE
sc_psort 

### ISSUE THREAD

**Issue by haghakhani** [cburstedde/libsc#11]
Hi Developers, 

Thank you for developing libsc and p4est libraries which are very well-written and useful. I have a question regarding sc_psort function in libsc that would appreciate your help. There is a comment in p4est_points.c which says that psort in libsc is buggy and git blame shows that comment goes back to 2010 (63bc736e (Carsten Burstedde 2010-09-29 10:28:14 -0500  25):

/********************************************************************
 *                          IMPORTANT NOTE                          *
 *                                                                  *
 * The p4est_points functionality depends on sc/src/sc_sort.        *
 * That parallel bitonic sort is still buggy (see sc/bugs).         *
 * If you want to use this code you have to fix the sort first.     *
 ********************************************************************/
However, there are many changes after that mainly by Sarah and for example with this comment message (d8d41bf Bitonic Sort Bug Fix). I am wondering that is still libsc buggy or now it's working fine? If it's now bug free, maybe is better to remove the misleading comment in p4est_points.c

Regards,
Hossein

**Comment by cburstedde** [comment]
Hossein,

> Thank you for developing libsc and p4est libraries which are very well-written and useful. I have a question regarding sc_psort function in libsc that would appreciate your help. There is a comment in p4est_points.c which says that psort in libsc is buggy and git blame shows that comment goes back to 2010 (63bc736e (Carsten Burstedde 2010-09-29 10:28:14 -0500  25):
> 
> /********************************************************************
>  *                          IMPORTANT NOTE                          *
>  *                                                                  *
>  * The p4est_points functionality depends on sc/src/sc_sort.        *
>  * That parallel bitonic sort is still buggy (see sc/bugs).         *
>  * If you want to use this code you have to fix the sort first.     *
>  ********************************************************************/
> However, there are many changes after that mainly by Sarah and for example with this comment message (d8d41bf Bitonic Sort Bug Fix). I am wondering that is still libsc buggy or now it's working fine? If it's now bug free, maybe is better to remove the misleading comment in p4est_points.c

thanks for your question.

sc_sort may be fine, but we didn't test this sufficiently.  Please feel free to
use it and fix it if you find anything that is not working right.

We'll be grateful for you looking into it.

Best regards,

Carsten

**Comment by haghakhani** [comment]
Hi Carsten,

Thank you for the quick reply. I'll give it a shot and let you know if I see anything wrong.

Regards,
Hossein

**Comment by cburstedde** [comment]
> Thank you for the quick reply. I'll give it a shot and let you know if I see anything wrong.

Hossein, this will be great.

If you could begin with the latest feature-psort branch of libsc, you will be
using the most recent code.  Feel free to improve on the function as required.

**Comment by haghakhani** [comment]
Dear Carsten,

Thank you for creating that dev branch to test psort. I just wanted to let you know, I used that function to sort the continuous nodes in mangll to lexicographical order from the global index (which should be close to Morton order) and vice versa. As far as I have tested I've not seen any problem. I should add that in my tests I didn't use OpenMP and any other form of threading. I also wanted to make a small contribution by adding a test suit for psort but I noticed this test already exists. There are some minor issues in that file that I'll fix and submit a pull request. Please let me know if I can help further.

Thank you again.

Regards,
Hossein

**Comment by cburstedde** [comment]
Looking into the test program will be great. Thanks!

**Comment by cburstedde** [comment]
Any news? :)

**Comment by haghakhani** [comment]
Dear Carsten,

Thank you for the reminder. I am terribly sorry that I completely forgot to
get back to you on this issue. I was able to successfully use psort and it
was working fine. Let me check if I made any change to the test suit and
get back to you this weekend. This time I promise :-). Stay safe.

Regards,
Hossein

**Comment by haghakhani** [comment]
Dear Carsten, my apologies again for the delay, I submitted a pull request for this issue which I hope that it helps. Please take a look and feel free to accept/reject any changes. The test was printing the vectors after the sort, I thought that it might be good to print them also before the sort to visually verify the action of sc_psort. Since the test itself verifies the sorted values by gathering the vectors in the master rank and also having too many prints may a bit slowdown the testing processes please let me know if you want me to remove them. Thank you.

#19

**Comment by cburstedde** [comment]
Dear Hossein,

> Dear Carsten, my apologies again for the delay, I submitted a pull request for this issue which I hope that it helps. Please take a look and feel free to accept/reject any changes. The test was printing the vectors after the sort, I thought that it might be good to print them also before the sort to visually verify the action of sc_psort. Since the test itself verifies the sorted values by gathering the vectors in the master rank and also having too many prints may a bit slowdown the testing processes please let me know if you want me to remove them. Thank you.

thanks for your work.  I'm looking forward to merge your changes to the test.
The changes to the logs will break backwards compatibility of all output and
confuse a lot of people, even though the idea is nice.  Can I ask you to push a
branch feature-psort and add a file doc/author_aghakhani.txt stating that your
code is BSD?

**Comment by haghakhani** [comment]
Dear Carsten,

Thank you for your kind words. It was my pleasure to make a very small contribution. I added the file and along with the other commit that I made earlier for the psort test pushed to the feature-psort branch on my forked repository, the following is the pull request to that branch:
#21

**Comment by cburstedde** [comment]
Dear Hossein,

> Thank you for your kind words. It was my pleasure to make a very small contribution. I added the file and along with the other commit that I made earlier for the psort test pushed to the feature-psort branch on my forked repository, the following is the pull request to that branch:
> #21 

I've smoothed it over a bit -- a good opportunity to look at the test program.

Your contribution is now merged to develop.  Thanks again!

**Comment by haghakhani** [comment]
No problem, thank you and all other contributors for developing such a handy and lightweight library. 
So I think we can close this issue.

**Comment by cburstedde** [comment]
> Thank you for your kind words. It was my pleasure to make a very small contribution. I added the file and along with the other commit that I made earlier for the psort test pushed to the feature-psort branch on my forked repository, the following is the pull request to that branch:
> #21 

One more idea: the test fails with a sort count of 0 (this cannot be done with
the command line, but provoked by hacking).  Would you enjoy repairing this?

Basically, the test should work fine if any or all local counts are 0.

**Comment by haghakhani** [comment]
Oh! you are right. I didn't test it for that case. 
Sure, I can fix it and let you know when I am done.

**Comment by cburstedde** [comment]
I've had some merge acrobatics since I like this branch to be on top of develop (v2.2). If you work on this again, please use my latest feature-psort as starting point.

**Comment by haghakhani** [comment]
Dear Carsten,

Sure, I will, and thank you for letting me know. I have been very busy the
past few weeks including the weekends but I have not forgotten this. I'll
revisit the issue that you mentioned in the psort and will fix it.

**Comment by cburstedde** [comment]
Thanks, the code is updated and fine to use.
