### ISSUE TITLE
project version is 0.0.0 when compiling libsc from git tarball

### ISSUE THREAD

**Issue by topazus** [cburstedde/libsc#134]
**Description**

<details>
<summary>build log</summary>

```bash
ruby in 🌐 fedora in rpmbuild/SOURCES/libsc-83bd019fc9f029a9c15a3ae823e6d7d20e6e0340 via △ v3.27.0-rc4 
❯ cmake . -B build -GNinja -DCMAKE_BUILD_TYPE=Release -Dzlib=OFF -DCMAKE_SKIP_RPATH=ON -DBUILD_SHARED_LIBS=ON && cmake --build build -j6
-- The C compiler identification is GNU 13.1.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib64/ccache/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- libsc 0.0.0 install prefix: /home/ruby/rpmbuild/SOURCES/libsc-83bd019fc9f029a9c15a3ae823e6d7d20e6e0340/build/local
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.13")  
-- Using system zlib : 1.2.13
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Could NOT find jansson (missing: jansson_DIR)
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.9.5") 
-- jansson library found via pkg-config
-- Looking for sqrt
-- Looking for sqrt - not found
-- Looking for sqrt
-- Looking for sqrt - found
-- Looking for realloc
-- Looking for realloc - found
-- Looking for aligned_alloc
-- Looking for aligned_alloc - found
-- Looking for backtrace
-- Looking for backtrace - found
-- Looking for backtrace_symbols
-- Looking for backtrace_symbols - found
-- Looking for execinfo.h
-- Looking for execinfo.h - found
-- Looking for fsync
-- Looking for fsync - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for posix_memalign
-- Looking for posix_memalign - found
-- Looking for basename
-- Looking for basename - found
-- Looking for qsort_r
-- Looking for qsort_r - found
-- Checking prototype qsort_r for SC_HAVE_GNU_QSORT_R
-- Checking prototype qsort_r for SC_HAVE_GNU_QSORT_R - True
-- Checking prototype qsort_r for SC_HAVE_BSD_QSORT_R
-- Checking prototype qsort_r for SC_HAVE_BSD_QSORT_R - False
-- Looking for fabs
-- Looking for fabs - found
-- Looking for signal.h
-- Looking for signal.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for random
-- Looking for random - found
-- Looking for srandom
-- Looking for srandom - found
-- Looking for strtoll
-- Looking for strtoll - found
-- Looking for strtok_r
-- Looking for strtok_r - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for sys/time.h
-- Looking for sys/time.h - found
-- Looking for time.h
-- Looking for time.h - found
-- Looking for libgen.h
-- Looking for libgen.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for getopt.h
-- Looking for getopt.h - found
-- Looking for sys/ioctl.h
-- Looking for sys/ioctl.h - found
-- Looking for sys/select.h
-- Looking for sys/select.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for linux/videodev2.h
-- Looking for linux/videodev2.h - found
-- Looking for linux/version.h
-- Looking for linux/version.h - found
-- Performing Test SC_ENABLE_V4L2
-- Performing Test SC_ENABLE_V4L2 - Success
-- Check size of int
-- Check size of int - done
-- Check size of unsigned int
-- Check size of unsigned int - done
-- Check size of long
-- Check size of long - done
-- Check size of long long
-- Check size of long long - done
-- Check size of unsigned long
-- Check size of unsigned long - done
-- Check size of unsigned long long
-- Check size of unsigned long long - done
-- Looking for SC_ENABLE_MPI
-- Looking for SC_ENABLE_MPI - not found
-- Looking for SC_ENABLE_MPIIO
-- Looking for SC_ENABLE_MPIIO - not found
-- Performing Test _has_wall
-- Performing Test _has_wall - Success
-- The following features have been enabled:

 * shared, shared libsc library

-- The following features have been disabled:

 * MPI, MPI features of libsc
 * OpenMP, OpenMP features of libsc
 * ZLIB, ZLIB features of libsc

-- Configuring done (3.5s)
-- Generating done (0.0s)
-- Build files have been written to: /home/ruby/rpmbuild/SOURCES/libsc-83bd019fc9f029a9c15a3ae823e6d7d20e6e0340/build
[73/73] Linking C executable test/sc_test_io_sink

ruby in 🌐 fedora in rpmbuild/SOURCES/libsc-83bd019fc9f029a9c15a3ae823e6d7d20e6e0340 via △ v3.27.0-rc4 
❯ find . -name 'libsc.so*'
./build/libsc.so.0.0.0
./build/libsc.so
```

</details>

**Proposed solution**

https://github.com/cburstedde/libsc/blob/83bd019fc9f029a9c15a3ae823e6d7d20e6e0340/CMakeLists.txt#L42-L43

It seemed this was casued due to that the project version was extracted by [git.cmake file](https://github.com/cburstedde/libsc/blob/master/cmake/git.cmake), the git.cmake file invoke `git-version-gen` which `git describe` does not have output. So the default project version will be 0.0.0 by default.

https://github.com/cburstedde/libsc/blob/83bd019fc9f029a9c15a3ae823e6d7d20e6e0340/cmake/git.cmake#L1-L9

https://github.com/cburstedde/libsc/blob/83bd019fc9f029a9c15a3ae823e6d7d20e6e0340/build-aux/git-version-gen#L138-L195

**Comment by topazus** [comment]
I think it will be simpler to just set project version with `VERSION` option in `project()` in CMakeLists.txt file.

**Comment by cburstedde** [comment]
git describe should be working (at least it does with autotools). Make sure to checkout the git history with tags.

**Comment by topazus** [comment]
@cburstedde The github source code archive does not include information of git history. [1] The library version with autotools is defined by the following lines:
https://github.com/cburstedde/libsc/blob/83bd019fc9f029a9c15a3ae823e6d7d20e6e0340/src/Makefile.am#L47-L49

[1] https://docs.github.com/en/repositories/working-with-files/using-files/downloading-source-code-archives#overview-of-source-code-archives

**Comment by cburstedde** [comment]
Thanks; pinging @pkestene to ask of both build systems may create the exact same version information in the library.

**Comment by pkestene** [comment]
Hi @topazus 

just a few remarks to sumarize before answering your question because there are actually two problems:

1. currently, both autotools agree on the "project" version, they both use the same logic; project version number is generated by bash script ` build-aux/git-version-gen`
2. however, as you noticed above, autotools and cmake differ in the way they suffix the shared library filename libsc.so.X.Y.Z. Indeed, autotools, uses libtool flag `-version-info 2:0:0` (so a hard code version number) while cmake (see top-level CMakeLists.txt) uses project's version as a suffix : `set_property(TARGET sc PROPERTY VERSION ${PROJECT_VERSION})`

I think we should just change the top-level CMakeLists.txt: `set_property(TARGET sc PROPERTY VERSION 2:0:0)`;or maybe  a more clean way would be to set the library version number "2:0:0" in a text file and make autotools and cmake read that file, so that the library version in only hardcoded once.
I can provide a patch for that.

Now there is still, the fact that on your machine the project version is 0.0.0, this may happen when building with cmake on a machine where either git is not available or building an archive file (not a git clone) that does not contain file .tarball-version. From the log above, I guess your are trying to build "develop" branch.

@cburstedde 
To make sure that project version is never 0.0.0, maybe that:
- each time, you want to tag a new version (currently latest tat is 2.8.5), the very last commit before tagging, we could update a file named .e.g .project-version-fallback which contains the current version number (generated using the logic as .tarball-version) 
- then this fallback number would only be used by cmake build when git is not available or using an archive that doesn't have a .tarball-version.
I may be wrong, please correct me if necessary.

**Comment by pkestene** [comment]
@topazus I guess you are using a github archive, right ?

**Comment by cburstedde** [comment]
Hi @pkestene, thanks for the analysis. I like the idea of putting the libtool version into a given file in the source tree. How would autoconf read this file? We'd need to make sure that this works for both out-of-source and in-source builds, and for builds from a git checkout as well as an autoconf-generated tarball.

**Comment by cburstedde** [comment]
@pkestene, maybe your second argument, however, indicates that it would be more robust to hardcode the library version for CMake in another prominent place that is hard to miss for the maintainer?

**Comment by cburstedde** [comment]
@topazus, I think it is fine to hardcode the libtool version into the library generated by CMake. If you like, you can propose a PR, making sure that you define the version as a variable in a prominent place that is easy to update.

**Comment by topazus** [comment]
> @topazus I guess you are using a github archive, right ?

Sorry for the late response. Yes, I used Github archive file at the time of the first comment

> ldconfig will look only at files that are named lib*.so* (for regular
> shared objects) or ld-*.so* (for the dynamic loader itself).  Other files
> will be ignored.  Also, ldconfig expects a certain pattern to how the
> symbolic links are set up, like this example, where the middle file
> (libfoo.so.1 here) is the SONAME for the library:
>
>     libfoo.so -> libfoo.so.1 -> libfoo.so.1.12

ref: https://manned.org/ldconfig

for libsc, the symbolic links with autotools are:

```bash
❯ ll ./src/.libs/libsc.so*
lrwxrwxrwx. 1 aurora aurora     14 Dec 18 22:05 ./src/.libs/libsc.so -> libsc.so.2.0.0
lrwxrwxrwx. 1 aurora aurora     14 Dec 18 22:05 ./src/.libs/libsc.so.2 -> libsc.so.2.0.0
-rwxr-xr-x. 1 aurora aurora 703856 Dec 18 22:05 ./src/.libs/libsc.so.2.0.0
```

So the `libsc.so.2` is the SONAME for libsc, which can indicate the ABI/API changes.

**Comment by cburstedde** [comment]
The comment by @pkestene from Aug 25 is pretty spot on. We just do not have agreed on whether to provide a fallback for the project version. Maybe it's ok to not have one, as long as a maintainer making a release has git available.

**Comment by cburstedde** [comment]
Thanks for helping us figure this out. We're putting the soversion into a configuration file that we maintain manually. The soversion for the library is derived from that by both automake and CMake.
