### ISSUE TITLE
sc_test_dmatrix test failing on some configurations

### ISSUE THREAD

**Issue by rubendibattista** [cburstedde/libsc#15]
I'm packaging `p4est` and `libsc` for EasyBuild (as separate packages). I managed to make them compile correctly but we're encountering some problems with the test `sc_test_dmatrix` failing on some architectures. 

Details here: https://github.com/easybuilders/easybuild-easyconfigs/pull/7816

Can it be related to recent random numbers commits?

**Comment by cburstedde** [comment]
> I'm packaging `p4est` and `libsc` for EasyBuild (as separate packages). I managed to make them compile correctly but we're encountering some probles with the test `sc_test_dmatrix` failing on some architectures. 
> 
> Details here: https://github.com/easybuilders/easybuild-easyconfigs/pull/7816
> 
> Can it be related to recent random numbers commits? 

How would --without-blas on the configure line of both p4est and sc work?
It's not needed for p4est itself.

**Comment by rubendibattista** [comment]
I'll try to check.

In facts I struggled quite a bit with that `--with-blas` config option. I had `OpenBLAS` compiled with `openmp` support, but even using `--with-openmp` I was getting errors (there are build reports in the post above).

I needed to force the `LIBS` var to include `-fopenmp` to make it compile against our `OpenBLAS`. 

I'll try without it and report back

**Comment by cburstedde** [comment]
> I'll try to check.
> 
> In facts I struggled quite a bit with that `--with-blas` config option. I had `OpenBLAS` compiled with `openmp` support, but even using `--with-openmp` I was getting errors (there are build reports in the post above).
> 
> I needed to force the `LIBS` var to include `-fopenmp` to make it compile against our `OpenBLAS`. 
> 
> I'll try without it and report back

Yes, the fortran support is on the way out of libsc.  Too much trouble.

**Comment by rubendibattista** [comment]
Without LAPACK and BLAS it seems to compile smoothly. Thanks for helping.

**Comment by rubendibattista** [comment]
Ehi @cburstedde, I thought the problem was solved but we're still getting it on some machines:
https://github.com/easybuilders/easybuild-easyconfigs/pull/7816

Could you help us understand what's wrong with that test?

**Comment by cburstedde** [comment]
Hi,

> Ehi @cburstedde, I thought the problem was solved but we're still getting it on some machines:
> https://github.com/easybuilders/easybuild-easyconfigs/pull/7816
> 
> Could you help us understand what's wrong with that test?

a quick solution would be to configure --without-blas.
We're thinking of ditching the fortran support long-term.

Deeper inspection of this problem will sadly have to wait a bit.  Good luck!

**Comment by rubendibattista** [comment]
Thank you for your answer @cburstedde. We should be already compiling without BLAS and LAPACK support ([log](https://gist.github.com/boegel/91a2384ff9802138035c7736f81b4767)]. 

In particular:
```
o---------------------------------------
| Checking libraries
o---------------------------------------
checking for library containing fabs... none required
checking for library containing adler32_combine... -lz
checking for library containing lua_createtable... no
configure: Checking BLAS
configure: Not using BLAS
configure: Checking LAPACK
configure: Not using LAPACK
checking for getopt... successful
checking for obstack... successful
checking for POSIX threads... not used
checking for OpenMP... checking for library containing omp_get_thread_num... -lgomp
successful
checking size of void *... (cached) 8
checking for aligned_alloc... yes
checking for posix_memalign... yes
checking for memory alignment option... SC_SIZEOF_VOID_P
```

**Comment by cburstedde** [comment]
> Ehi @cburstedde, I thought the problem was solved but we're still getting it on some machines:
> https://github.com/easybuilders/easybuild-easyconfigs/pull/7816
> 
> Could you help us understand what's wrong with that test?

Did I read correctly that you're using 2.8 versions of sc?  This is intended
for preparing future incompatible changes, and the API of new stuff may shift.

How would the current develop branches of p4est and libsc work, plus that
branch of sc that removes the MPI intra-node-communicator init?

**Comment by rubendibattista** [comment]
Yes, I'm using `sc` 2.8 together with `p4est` 2.2. I'm maybe hitting some version conflict somehow? 

I'll try to stick to the `sc` commit that is currently checked out in the `p4est ` `master` branch. I'll also try the `develop` branch of both projects and update here.

**Comment by boegel** [comment]
I'm seeing the `sc_test_dmatrix` test fail as shown below with the following setup:

* p4est 2.2 + libsc 2.2 (commit ID 5282025)
* configured with either:
  * `--without-blas --without-lapack`
  * `--with-blas=/path/to/libopenblas.a --with-lapack=/path/to/libopenblas.a` (and linking with `-fopenmp`)

The biggest issue here is not actually seeing the problem, there are no clear error messages that may explain the problem. How could we figure out more on the underlying cause?

```
FAIL: test/sc_test_dmatrix
==========================

[libsc] This is libsc UNKNOWN
[libsc] CPP                      mpicc -E
[libsc] CPPFLAGS                 -I/software/OpenBLAS/0.3.5-GCC-8.2.0-2.31.1/include -I/software/ScaLAPACK/2.0.2-gompi-2019a-OpenBLAS-0.3.5/include -I/software/FFTW/3.3.8-gompi-2019a/include -I/software/zlib/1.2.11-GCCcore-8.2.0/include -I/software/METIS/5.1.0-GCCcore-8.2.0/include
[libsc] CC                       mpicc
[libsc] CFLAGS                   -O2 -ftree-vectorize -march=native -fno-math-errno -fopenmp
[libsc] LDFLAGS                  -L/software/GCCcore/8.2.0/lib64 -L/software/GCCcore/8.2.0/lib -L/software/OpenBLAS/0.3.5-GCC-8.2.0-2.31.1/lib -L/software/ScaLAPACK/2.0.2-gompi-2019a-OpenBLAS-0.3.5/lib -L/software/FFTW/3.3.8-gompi-2019a/lib -L/software/zlib/1.2.11-GCCcore-8.2.0/lib -L/software/METIS/5.1.0-GCCcore-8.2.0/lib
[libsc] LIBS                     /software/OpenBLAS/0.3.5-GCC-8.2.0-2.31.1/lib/libopenblas.a /software/OpenBLAS/0.3.5-GCC-8.2.0-2.31.1/lib/libopenblas.a -lz -lm -lpthread
[libsc] Shared memory node communicator size: 2
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[58056,1],0]
  Exit code:    2
--------------------------------------------------------------------------
FAIL test/sc_test_dmatrix (exit status: 2)
```

**Comment by cburstedde** [comment]
> Yes, I'm using `sc` 2.8 together with `p4est` 2.2. I'm maybe hitting some version conflict somehow? 

Usually such a mix works ok enough, but if the commit of the sc subrepo is not
the one registered in the p4est commit, there is no guarantee.

An exception to this rule are feature branches of sc, such as the one that
removes the intra-comm code.

> I'll try to stick to the `sc` commit that is currently checked out in the `p4est ` `master` branch. I'll also try the `develop` branch of both projects and update here.

**Comment by boegel** [comment]
I just noticed that not using `-march=native` fixes the failing test.

We've seen this before, the underlying cause is usually a problem with the test making a too strict comparison on floating-point values, which then fails on systems like Intel Haswell (AVX2) & newer...
