### ISSUE TITLE
development branch does not compile with MPITrampoline

### ISSUE THREAD

**Issue by jmark** [cburstedde/libsc#170]
The development branch cannot be compiled with the MPITrampoline ABI wrapper:
https://github.com/eschnett/MPItrampoline

I specifically need this to provide a broad support of platforms for our t8code Julia bindings.

I describe the problem with a specific example:

Within `mpi.h` provided by MPITrampoline `MPI_ERR_LASTCODE` is not a real compile-time constant. This is true
for all other MPI constants as well.

```
// mpi.h
extern int MPITRAMPOLINE_CONST MPI_ERR_LASTCODE
```

In `libsc` `MPI_ERR_LASTCODE` is used in enums:

```
// sc_mpi.h
#define sc_MPI_ERR_LASTCODE               MPI_ERR_LASTCODE`
```
and
```
// sc_sda.h
typedef enum sc_scda_ret
{
  SC_SCDA_FERR_SUCCESS = 0, /**< successful function call */
  SC_SCDA_FERR_FORMAT = sc_MPI_ERR_LASTCODE,  /**< File not conforming to the
                                                   \b scda format. */
[...]
};
```

This gives the following error:
![grafik](https://github.com/cburstedde/libsc/assets/10619309/cb01ae42-7b93-4741-8ed3-6e2b2049e1dd)

@lukasdreyer

**Comment by cburstedde** [comment]
Thanks;, let's discuss with @tim-griesbach how we may address this.

**Comment by jmark** [comment]
There is also a discussion going at the MPTrampoline side: https://github.com/eschnett/MPItrampoline/issues/37

**Comment by cburstedde** [comment]
We're working on remiving the use of MPI_ERR_LASTCODE as a constant.

We'll alse be deprecating the configuration with MPI but without MPI I/O, leaving either non-MPI operation or MPI operation with full MPI_File support. Any opinions on this step?

**Comment by cburstedde** [comment]
I've just merged work by @tim-griesbach not to rely on MPI_ERR_LASTCODE anymore.

We have deprecated the combo --enable-mpi --disable-mpiio. Does all else work for y'all?

**Comment by cburstedde** [comment]
> I've just merged work by @tim-griesbach not to rely on MPI_ERR_LASTCODE anymore.
> 
> We have deprecated the combo --enable-mpi --disable-mpiio. Does all else work for y'all?

We have merged a fix for these cases. About to release 2.8.6! Any comments?
