### ISSUE TITLE
Problems encountered when building libsc

### ISSUE THREAD

**Issue by UNSAT** [cburstedde/libsc#176]
**Description**
There is the process when building libsc with Cygwin:
1. clone the github code ;
2. run ./bootstrop ;
3. ./configure (without mpi)
4. make
5. make install
Because I encountered many problems when I reference the "readme.txt"，I just built libsc as the  general compilation and installation process.

**Additional information**
Operating system, build configuration, etc.
![1](https://github.com/cburstedde/libsc/assets/118416071/bbd220c6-2df0-4cf8-96c1-31d6df5692e8)

**Comment by UNSAT** [comment]
Thank you for your reply!

I have decided to stop attempting to build libsc on Cygwin due to several unresolved issues. However, after learning Linux, I believe I have successfully built glib, gts, and libsc on a virtual machine! The process is illustrated in Picture 1, and the results are shown in Picture 2.

I do have two questions though:

1. If I build libsc using "### Autotools," do I need to skip the "### CMake" process?

2. I cannot find libsc in my bin folder. Should I configure the environment variables?

I would be grateful if you could provide me with some advice.
![1](https://github.com/cburstedde/libsc/assets/118416071/9aab3a5f-3616-426c-bb3d-ebfaaf90cd7a)
![2](https://github.com/cburstedde/libsc/assets/118416071/5a021e0d-18af-4d60-950c-a3745bfd6458)

**Comment by elykwilliams** [comment]
@UNSAT 
CMake and Autotools  are two alternative methods to compile and install. If you're having trouble with one you can always try the other. 

As for seeing libsc in your bin, it looks like your library was installed to `/home/future/libsc-master/local/` (the default location, you can override this with `./configure --prefix=/path/to/install`). If you look in `/home/future/libsc-master/local/lib` you should see `libsc.a`, as well as all the headers in `/home/future/libsc-master/local/include` . 

On the related issue of Cygwin support, it looks like you will have a difficult time installing shared libs on Cygwin, but static libraries worked fine for me (without MPI) using the latest Cygwin install and all of the Cygwin develop packages installed. 

I wasn't able to replicate the git-version "UNKOWN", can I ask what you did to clone the repository?

**Comment by cburstedde** [comment]
> As for seeing libsc in your bin, it looks like your library was installed to `/home/future/libsc-master/local/` (the default location, you can override this with `./configure --prefix=/path/to/install`). If you look in `/home/future/libsc-master/local/lib` you should see `libsc.a`, as well as all the headers in `/home/future/libsc-master/local/include` .

`configure --disable-shared` makes sure that we only generate the `.a` files and not the `.so` ones.

> On the related issue of Cygwin support, it looks like you will have a difficult time installing shared libs on Cygwin, but static libraries worked fine for me (without MPI) using the latest Cygwin install and all of the Cygwin develop packages installed.

**Comment by cburstedde** [comment]
Any news? Is there anything we can do to help?
