### ISSUE TITLE
Compiling libsc with openMPI using CMake fails to find `MPI_COMM_TYPE_SHARED`

### ISSUE THREAD

**Issue by maelk3** [cburstedde/libsc#195]
**Description**
Compiling libsc with openMPI using the CMake build system does not find `MPI_COMM_TYPE_SHARED`. Down the line, on t8code, this causes issues  DLR-AMR/t8code#1109 with shared memory usage.

**To Reproduce**
```
cmake ..  -Dmpi=ON
```

**Additional information**
The issue stems from the fact that `MPI_COMM_TYPE_SHARED` is defined as part of an anonymous enum on openMPI's `mpi.h` header file (instead of a macro definition), and the CMake function `check_symbol_exists` only checks for macro definition. A easy solution would be to use `check_c_source_compiles` instead. I would be glad to provide a pull request if this issue is considered.

**Comment by cburstedde** [comment]
Thanks for the report!

We had this type of error before on a different matter. @tim-griesbach, do you see a solution to this issue?

**Comment by tim-griesbach** [comment]
> We had this type of error before on a different matter. @tim-griesbach, do you see a solution to this issue?

I think that @maelk3's proposal of creating a PR to use `check_c_source_compiles` instead of `check_symbol_exists` is a good solution. It is also aligned with the [recommendation](https://cmake.org/cmake/help/latest/module/CheckSymbolExists.html) of the CMake documentation for checking enums.

**Comment by cburstedde** [comment]
Please go for it @maelk3. This will be good to fix! Compile-link-checking is sensible for all MPI functionalities that presently use symbol_exists, as well as for qsort_r: The latter has two different conventions flying around, one from BSD and one GNU. Please see the autoconf code in config/sc_qsort.m4 in case you like to address the latter as well.

**Comment by cburstedde** [comment]
This has been addressed quickly thanks to @maelk3. :)
