### ISSUE TITLE
Typo in the CMake build system

### ISSUE THREAD

**Issue by maelk3** [cburstedde/libsc#198]
While tinkering with libsc's CMake build system, I stumbled upon this code snippet:

https://github.com/cburstedde/libsc/blob/d147b82044b3a42ae223dc7c007662e757f80994/cmake/config.cmake#L100-L106

There, the if statement is always taken as the `$` is missing before `CACHE{SC_ENABLE_MPI}` and thus treats  `CACHE{SC_ENABLE_MPI}` as a string literal and not the value of the cached variable `SC_ENABLE_MPI`. A simple fix could be:

```
if(NOT "${SC_ENABLE_MPI}" EQUAL "$CACHE{SC_ENABLE_MPI}")
```
Here the extra quotes are necessary so that when either of the two compared variables is empty, the correct number of parameters is specified to the equal operator, empty variables being treated as empty string literals.

**Comment by cburstedde** [comment]
Thanks! Would you like to propose a PR?

**Comment by maelk3** [comment]
Sure!

**Comment by cburstedde** [comment]
Thanks for the report and the fix! Is there anything similar to be addressed in p4est?

**Comment by maelk3** [comment]
My pleasure! I have not found anything similar in p4est.

**Comment by cburstedde** [comment]
> My pleasure! I have not found anything similar in p4est.

Thanks so much!  I've now updated libsc develop in p4est.
