### ISSUE TITLE
Error in configure tests for BLAS/LAPACK

### ISSUE THREAD

**Issue by carlodefalco** [cburstedde/libsc#27]
Hi,

I'm trying to build p4est on macos 11.1  using openblas for the blas/lapack dependency.
configure fails with error :

`checking for BLAS by linking a C program without FLIBS... failed`
`checking for BLAS by linking a C program with FLIBS... failed`
`configure: error: Cannot find BLAS library, specify a path using LIBS=-L<DIR> (ex. LIBS=-L/usr/path/lib) or a specific library using BLAS_LIBS=DIR/LIB (for example BLAS_LIBS=/usr/path/lib/libcxml.a)`

the failing autoconf test has the following error : 

`conftest.c:80:1: error: implicit declaration of function 'dgemm_' is invalid in C99 [-Werror,-Wimplicit-function-declaration]`
`dgemm_ ("N", "N", &i, &i, &i, &alpha, &A, &i, &B, &i, &beta, &C, &i);`
`^`
`1 error generated.`

looking at the test code, the issue seems not to be with my blas library but rather in the test lines below : 

https://github.com/cburstedde/libsc/blob/master/config/sc_blas.m4#L85-L89

it looks quite clear that the `#endif` should be moved between lines 86 and 87 or the function prototype
would be missing when compiling that code with a C99 compiler.

A similar issue seems to hold for sc_lapack.m4 as well : 

https://github.com/cburstedde/libsc/blob/master/config/sc_lapack.m4#L82

Hope this helps,
c.

P.S.: Notice that this issue is not specific to macos 11.1 (or more precisely XCode 12) it is just showing
up on this new system because in the latest release Apple made the option 

    -Werror=implicit-function-declaration

on by default. It should be possible to trigger the same error on other systems by adding the
above option to CFLAGS.

**Comment by cburstedde** [comment]
Thanks a lot, I've followed your suggestions and updated the develop branch. How does it work for you?

**Comment by carlodefalco** [comment]
Hi, I tested the "develop" branch and it works now, thanks!
