### ISSUE TITLE
p4est/sc 2.3.1: Trouble with VFL2

### ISSUE THREAD

**Issue by marcfehling** [cburstedde/libsc#45]
**Description/To Reproduce**
Building `p4est`/`sc` yields errors related to `v4l2` during compilation for unknown reasons.

**Additional information**
I build `p4est` using the [`p4est-setup.sh`](https://github.com/dealii/dealii/blob/master/doc/external-libs/p4est-setup.sh) script from the `deal.II` project.

On my local notebook (`archlinux`, `kernel 5.12.9-arch1-1`, `gcc 11.1.0`, `v4l-utils 1.20.0`) compilation passes successfully.

On our workstation however (`CentOS 7`, `kernel 3.10.0-1160.25.1.el7.x86_64`, `gcc 8.1.0`, `vfl ?`), I get the following errors:
```
/raid/fehling/packages/p4est-2.3.1/sc/src/sc_v4l2.c: In function ‘sc_v4l2_device_format’:
/raid/fehling/packages/p4est-2.3.1/sc/src/sc_v4l2.c:276:10: error: ‘struct v4l2_pix_format’ has no member named ‘ycbcr_enc’
   vd->pix->ycbcr_enc = V4L2_YCBCR_ENC_DEFAULT;
          ^~
/raid/fehling/packages/p4est-2.3.1/sc/src/sc_v4l2.c:276:24: error: ‘V4L2_YCBCR_ENC_DEFAULT’ undeclared (first use in this function); did you mean ‘V4L2_PRIORITY_DEFAULT’?
   vd->pix->ycbcr_enc = V4L2_YCBCR_ENC_DEFAULT;
                        ^~~~~~~~~~~~~~~~~~~~~~
                        V4L2_PRIORITY_DEFAULT
/raid/fehling/packages/p4est-2.3.1/sc/src/sc_v4l2.c:276:24: note: each undeclared identifier is reported only once for each function it appears in
/raid/fehling/packages/p4est-2.3.1/sc/src/sc_v4l2.c:277:10: error: ‘struct v4l2_pix_format’ has no member named ‘quantization’
   vd->pix->quantization = V4L2_QUANTIZATION_DEFAULT;
          ^~
/raid/fehling/packages/p4est-2.3.1/sc/src/sc_v4l2.c:277:27: error: ‘V4L2_QUANTIZATION_DEFAULT’ undeclared (first use in this function); did you mean ‘V4L2_PRIORITY_DEFAULT’?
   vd->pix->quantization = V4L2_QUANTIZATION_DEFAULT;
                           ^~~~~~~~~~~~~~~~~~~~~~~~~
                           V4L2_PRIORITY_DEFAULT
/raid/fehling/packages/p4est-2.3.1/sc/src/sc_v4l2.c:278:10: error: ‘struct v4l2_pix_format’ has no member named ‘xfer_func’
   vd->pix->xfer_func = V4L2_XFER_FUNC_DEFAULT;
          ^~
/raid/fehling/packages/p4est-2.3.1/sc/src/sc_v4l2.c:278:24: error: ‘V4L2_XFER_FUNC_DEFAULT’ undeclared (first use in this function); did you mean ‘V4L2_PRIORITY_DEFAULT’?
   vd->pix->xfer_func = V4L2_XFER_FUNC_DEFAULT;
                        ^~~~~~~~~~~~~~~~~~~~~~
                        V4L2_PRIORITY_DEFAULT
make[1]: *** [src/libsc_la-sc_v4l2.lo] Error 1
```

The `sc_config.h` file shows that `V4L2` has indeed been found:
```
p4est/sc/config/sc_config.h
---------------------------
/* Development with V4L2 devices works */
#ifndef SC_ENABLE_V4L2
#define SC_ENABLE_V4L2 1
#endif
```

Indeed, `vfl2` is available on the system.
```
usr/lib64/libv4l2rds.so.0
usr/lib64/libv4l2.so.0
usr/lib64/libv4l2.so.0.0.0
usr/lib64/libv4l/v4l2convert.so
usr/lib64/libv4l2rds.so.0.0.0
```

Maybe it's an outdated version of the `vfl2` library on our workstation that is not compatible with p4est/sc?

**Comment by marcfehling** [comment]
It seems like they changed the struct `v4l2_pix_format` with kernel 3.17 (see [changelog](https://www.kernel.org/doc/html/v4.12/media/uapi/v4l/hist-v4l2.html#v4l2-in-linux-3-17)).

That could explain the incompatibility, as our workstation runs on `kernel 3.10`.

**Comment by bangerth** [comment]
Doesn't this dependency of SC on V4L also tie p4est to Linux only? How is this translated to Macs and Windows operating systems?

**Comment by cburstedde** [comment]
> Doesn't this dependency of SC on V4L also tie p4est to Linux only? How is this translated to Macs and Windows operating systems?

The linux/.h file  is not detected on Windows/MacOS, so nothing is compiled.

That said, I should make this feature disabled by default, as it is really of very
special use only, and we all like backward compatibility.  Thanks for the report!

**Comment by cburstedde** [comment]
> It seems like they changed the struct `v4l2_pix_format` with kernel 3.17 (see [changelog](https://www.kernel.org/doc/html/v4.12/media/uapi/v4l/hist-v4l2.html#v4l2-in-linux-3-17)).
> 
> That could explain the incompatibility, as our workstation runs on `kernel 3.10`.

If you want to PR a minimal #ifdef on linux header versions >= 4 to enable it,
I'll be happy to look at it.

**Comment by marcfehling** [comment]
> That said, I should make this feature disabled by default, as it is really of very
special use only, and we all like backward compatibility.  Thanks for the report!

Yes, it would indeed be nice to keep it disabled by default and only enable it on demand via `autoconf`.

> If you want to PR a minimal #ifdef on linux header versions >= 4 to enable it,
I'll be happy to look at it.

This particular guard makes sense, independent of making the feature optional via `autoconf`. We could either disable the feature if the headers are too old, or use the old interface of `V4L2`. I'm quite involved at the moment, I hope I can get back to it in a couple of weeks.

**Comment by cburstedde** [comment]
> > That said, I should make this feature disabled by default, as it is really of very
> special use only, and we all like backward compatibility.  Thanks for the report!
> 
> Yes, it would indeed be nice to keep it disabled by default and only enable it on demand via `autoconf`.

I'll keep this on the list.  For now, I've added checks that should filter
out older versions.  Does the libsc feature-check-v4l2 branch work for you?
If yes, I'll merge it into master, develop, and prev3-develop.

> > If you want to PR a minimal #ifdef on linux header versions >= 4 to enable it,
> I'll be happy to look at it.
> 
> This particular guard makes sense, independent of making the feature optional via `autoconf`. We could either disable the feature if the headers are too old, or use the old interface of `V4L2`. I'm quite involved at the moment, I hope I can get back to it in a couple of weeks.

**Comment by marcfehling** [comment]
> Does the libsc feature-check-v4l2 branch work for you?

I can confirm that a custom p4est tarball with that particular branch compiles on the problematic machines. Thank you!

**Comment by cburstedde** [comment]
Thanks, I've updated to v2.3.2 accordingly. Disabling by default is on the back burner but should be easy enough.
