### ISSUE TITLE
Missing #include <stdio.h> in sc_io.c

### ISSUE THREAD

**Issue by bangerth** [cburstedde/libsc#65]
A follow-up to https://github.com/cburstedde/p4est/issues/133:
```
/home/saspark2/build2//tmp/unpack/p4est-2.3.2/sc/src/sc_io.c(581): warning #266: function "fileno" declared implicitly
    retval = fsync (fileno (file));
                    ^
```
This corresponds to the following lines: https://github.com/cburstedde/libsc/blob/8a67e32e3fb556b4c9c7d51720625035d3caa72c/src/sc_io.c#L572-L586 . `fileno` is declared in `<stdio.h>`, I think the file is just missing the corresponding `#include`.

**Comment by cburstedde** [comment]
We do inclued stdio.h, but the fileno function may require a feature test macro depending on the C library.

Suggesting to deactivate both the fflush and fsync parts of the function and to rely on fclose alone. That should be sufficient to have synchronized data iin the functions using it (p4est_save_ext). Would you agree?

**Comment by bangerth** [comment]
I've got no opinion on the matter -- whatever it takes to make this compile is fine with me :-)

**Comment by chronictectonic** [comment]
I tried the suggestion to deactivate fflush and fsync parts and was able to move forward.

Thanks!

**Comment by cburstedde** [comment]
Cool, me too. We'll merge this soonish.

**Comment by cburstedde** [comment]
This should now be fixed. Everything compiles fine now?

**Comment by cburstedde** [comment]
I'd be hoping this issue is gone now as well.
