### ISSUE TITLE
Missing declaration for M_PI in sc_random.c

### ISSUE THREAD

**Issue by bangerth** [cburstedde/libsc#66]
Another follow-up to https://github.com/cburstedde/p4est/issues/133:
```
/home/saspark2/build2//tmp/unpack/p4est-2.3.2/sc/src/sc_random.c(153): error: identifier "M_PI" is undefined
        t = tan (M_PI * sc_rand (state));
                 ^
```
This corresponds to https://github.com/cburstedde/libsc/blob/8a67e32e3fb556b4c9c7d51720625035d3caa72c/src/sc_random.c#L135-L163 . I'm a bit stumped how the compiler knows about `tan` but not `M_PI`. It does seem like there is no `#include <math.h>` anywhere, though.

**Comment by cburstedde** [comment]
Apparently M_PI is not part of any standard, just a convention. We'll look into defining it if not yet defined like

    #ifndef M_PI
    #define M_PI 3.456
    #endif

Would that work?

**Comment by bangerth** [comment]
Close enough :-)

**Comment by cburstedde** [comment]
Ok we're on it.

**Comment by cburstedde** [comment]
Should be merged now. Everything compiles ok?

**Comment by bangerth** [comment]
I don't have a system to test this one. @chronictectonic might have, though.

**Comment by cburstedde** [comment]
I'm closing this; please feel free to reopen or make another issue if needed. Thanks for the report!
