### ISSUE TITLE
Linking error caused by -static

### ISSUE THREAD

**Issue by dmdu** [cburstedde/libsc#9]
In the process of building ForestClaw on Edison at NERSC, Jed Brown and I have run into the following issue.

dmdu@edison12:~/forestclaw-build> cc --version
gcc (GCC) 6.1.0 20160427 (Cray Inc.)
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

dmdu@edison12:~/forestclaw-build> cc -craype-verbose
gcc -march=corei7-avx -static -D__CRAYXC -D__CRAY_IVYBRIDGE -D__CRAYXT_COMPUTE_LINUX_TARGET -upthread_mutex_destroy -D__TARGET_LINUX__ -I/opt/cray/libsci/16.07.1/GNU/5.1/x86_64/include -I/opt/cray/mpt/7.4.1/gni/sma/include -I/opt/cray/mpt/7.4.1/gni/mpich-gnu/5.1/include -I/usr/common/usg/libtool/2.4.6/include -I/opt/cray/rca/1.0.0-2.0502.57212.2.56.ari/include -I/opt/cray/alps/5.2.3-2.0502.9295.14.14.ari/include -I/opt/cray/xpmem/0.1-2.0502.57015.1.15.ari/include -I/opt/cray/gni-headers/4.0-1.0502.10317.9.2.ari/include -I/opt/cray/dmapp/7.0.1-1.0502.10246.8.47.ari/include -I/opt/cray/pmi/5.0.10-1.0000.11050.0.0.ari/include -I/opt/cray/ugni/6.0-1.0502.10245.9.9.ari/include -I/opt/cray/udreg/2.3.2-1.0502.9889.2.20.ari/include -I/usr/local/include -I/opt/cray/wlm_detect/1.0-1.0502.57063.1.1.ari/include -I/opt/cray/krca/1.0.0-2.0502.57202.2.45.ari/include -I/opt/cray-hss-devel/7.2.0/include -L/opt/cray/libsci/16.07.1/GNU/5.1/x86_64/lib -L/opt/cray/mpt/7.4.1/gni/sma/lib64 -L/opt/cray/dmapp/default/lib64 -L/opt/cray/mpt/7.4.1/gni/mpich-gnu/5.1/lib -L/usr/common/usg/libtool/2.4.6/lib -L/opt/cray/rca/1.0.0-2.0502.57212.2.56.ari/lib64 -L/opt/cray/alps/5.2.3-2.0502.9295.14.14.ari/lib64 -L/opt/cray/xpmem/0.1-2.0502.57015.1.15.ari/lib64 -L/opt/cray/dmapp/7.0.1-1.0502.10246.8.47.ari/lib64 -L/opt/cray/pmi/5.0.10-1.0000.11050.0.0.ari/lib64 -L/opt/cray/ugni/6.0-1.0502.10245.9.9.ari/lib64 -L/opt/cray/udreg/2.3.2-1.0502.9889.2.20.ari/lib64 -L/usr/common/das/darshan/2.3.1/lib -L/opt/cray/atp/2.0.2/libApp -L/usr/local/lib -L/opt/cray/wlm_detect/1.0-1.0502.57063.1.1.ari/lib64 -Wl,--no-as-needed,-lAtpSigHandler,-lAtpSigHCommData -Wl,--undefined=_ATP_Data_Globals -Wl,--undefined=__atpHandlerInstall -lpthread -Wl,-u,MPI_Init,-u,MPI_Wtime,-u,__wrap_H5Fcreate,-u,__wrap_ncmpi_create,-wrap,write,-wrap,open,-wrap,creat,-wrap,creat64,-wrap,open64,-wrap,close,-wrap,read,-wrap,lseek,-wrap,lseek64,-wrap,pread,-wrap,pwrite,-wrap,readv,-wrap,writev,-wrap,__xstat,-wrap,__lxstat,-wrap,__fxstat,-wrap,__xstat64,-wrap,__lxstat64,-wrap,__fxstat64,-wrap,mmap,-wrap,mmap64,-wrap,fopen,-wrap,fclose,-wrap,fread,-wrap,fwrite,-wrap,fseek,-wrap,fopen64,-wrap,pread64,-wrap,pwrite64,-wrap,fsync,-wrap,fdatasync,-wrap,ncmpi_create,-wrap,ncmpi_open,-wrap,ncmpi_close,-wrap,H5Fcreate,-wrap,H5Fopen,-wrap,H5Fclose,-wrap,aio_write,-wrap,aio_write64,-wrap,aio_read,-wrap,aio_read64,-wrap,lio_listio,-wrap,lio_listio64,-wrap,aio_return,-wrap,aio_return64,-wrap,mkstemp,-wrap,mkostemp,-wrap,mkstemps,-wrap,mkostemps -lfmpich -lmpichcxx -Wl,--start-group -ldarshan-mpi-io -ldarshan-posix -ldarshan-stubs -Wl,--end-group -lz -lsci_gnu_51_mpi -lsci_gnu_51 -lmpich_gnu_51 -lrt -lugni -lpthread -lpmi -lsci_gnu_51 -lsma -lpmi -ldmapp -lpthread -lxpmem -ludreg -lpmi -lpthread -lalpslli -lpthread -lwlm_detect -lugni -lpthread -lalpsutil -lpthread -lrca -lltdl -ldl -Wl,--as-needed,-lgfortran,-lquadmath,--no-as-needed -Wl,--as-needed,-lm,--no-as-needed -Wl,--as-needed,-lpthread,--no-as-needed

“-static” in this list prevents linking with the shared libraries and causes this error:

dmdu@edison12:~/forestclaw-build> make
Making all in sc
make[1]: Entering directory `/global/u2/d/dmdu/forestclaw-build/sc'
/bin/sh ./libtool  --tag=CC   --mode=link cc  -O3 -Wall -std=c99 -pedantic   -o libb64/sc_b64dec libb64/libb64_sc_b64dec-b64dec.o ./src/libsc.la -lgomp
libtool: link: cc -O3 -Wall -std=c99 -pedantic -o libb64/sc_b64dec libb64/libb64_sc_b64dec-b64dec.o  ./src/.libs/libsc.a /opt/gcc/6.1.0/snos/lib/../lib64/libgomp.so -lrt -ldl -Wl,-rpath -Wl,/opt/gcc/6.1.0/snos/lib/../lib64 -Wl,-rpath -Wl,/opt/gcc/6.1.0/snos/lib/../lib64
/usr/bin/ld: attempted static link of dynamic object `/opt/gcc/6.1.0/snos/lib/../lib64/libgomp.so'
collect2: error: ld returned 1 exit status
make[1]: *** [libb64/sc_b64dec] Error 1
make[1]: Leaving directory `/global/u2/d/dmdu/forestclaw-build/sc'
make: *** [all-recursive] Error 1

config.log is below.

[config.txt](https://github.com/cburstedde/libsc/files/731266/config.txt)

**Comment by cburstedde** [comment]
I've received another independent bug report on omp linker issues.  Will
look into it soon.

Thanks! /Carsten

**Comment by dmdu** [comment]
Sounds good. Let me know how and when I can help with the testing.

Thanks!

**Comment by cburstedde** [comment]
Pleas check out the branch fix-config-openmp. Changes:
No CFLAGS are supplied by default. If you want them, do --enable-openmp="your C flags."
The link test for openmp is only done when --enable-openmp is present. It tries to link without any libraries first, then with -lgomp. If you want to avoid the gomp, supply configure LIBS="-lyouromp" ... and it should use this and find it when linking with nothing.
The default is now to not link test openmp at all.
Please let me know if this works better.

**Comment by cburstedde** [comment]
Any news? I'd close this issue if no.

**Comment by cburstedde** [comment]
Cool, thanks.
