### ISSUE TITLE
CMake: build Zlib instead of find

### ISSUE THREAD

**Issue by scivision** [cburstedde/libsc#96]
## Description

CMake-based users of libsc (and higher-level libraries using libsc) have noticed issues with ABI compatibility of Zlib. This is not a CMake-specific issue, but to resolve this we are creating a PR that when `-Dzlib=true` (default true) Zlib is automatically downloaded and built first.

**Comment by cburstedde** [comment]
Cool. Default true seems to be the right thing.
What if -Dzlib is not there -- is there a way to "just" use the one on the system without building it?

**Comment by scivision** [comment]
We could make "zlib" a text variable with three possibilities:

* not defined or false-like (e.g. false, 0): do not find or build zlib
* "find": find Zlib, build if not found
* "build: always build Zlib, don't try to find it.

**Comment by cburstedde** [comment]
Thanks, good to know this is a possibility. Here I'd prefer it simple (boolean). Imho we do not really need to enable a foricible false configuration. What about:

 - If the option is not given, we test for availability and base the #defines on that.
 - If the option is given, we build. Maybe a descriptive name will be -Dzlib_build or similar?

If you were in the position to replicate this functionality with libjansson (as far as it is cross-platform), for the defines SC_HAVE_JANSSON_H and SC_HAVE_JANSSON, that would be perfect.

**Comment by cburstedde** [comment]
After some expremintation, I agree it's best to stick to just one #define per library, scratching SC_HAVE_*_H.

**Comment by pkestene** [comment]
hi @cburstedde @scivision 
I ran into the same problem recently (see https://github.com/cburstedde/p4est/issues/198).

I think it would be good (for maximum flexibility) to offer the possibility of using the system zlib, especially if there no strong requirement upon the version of zlib, the one from the system should be preferred. 
If the user prefer to build zlib, ok, but it should be knowingly.

If the system provide all the requirements to build libsc (as zlib), we should first try to use them.

**Comment by cburstedde** [comment]
This seems as desired now. Compatible with latest p4est/other comments?
